name: Retrain Model (Weekly)

on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at midnight
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate features
      run: python fetch_features.py

    - name: Train model
      run: python train_rain_model.py

    - name: Commit and push new model
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add rain_model.pkl
        git commit -m "Auto: retrained model update" || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
